---
# tasks file for apache2


- name: Install tool
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-httplib2

##### This is use the with_dict loop
##### with_dict loop the key of sites which is app1, app2
##### and we will use value of the key like below
- name: Install Nginx and Mysql
  apt: 
    name: "{{item.value.image}}"
    state: "{{item.value.repo}}"
    #update_cache: yes
  with_dict:
    - "{{ sites }}"

#- name: Install Mysql-server
#  apt:
#    name: mysql-server
#    state: present
#    #update_cache: yes
#  with_dict:
#    - sites

- name: Ensure Mysql started
  service:
    name: mysql
    state: started
    enabled: yes
- name: verify AWX response
  uri:
    url: "http://{{item}}"
    return_content: yes
  with_items:
    - "20.198.234.27"
  register: lb_index
- fail: msg="Index failed to return content"
  when: "'html' not in item.content"
  with_items:
    - "{{ lb_index.results }}"
- name: verify Stackstorm response
  uri:
    url: "https://{{item}}"
    return_content: yes
    validate_certs: no
  with_items:
    - "52.139.216.235"
  register: lb_index
- fail: msg="Index failed to return content"
  when: "'html' not in item.content"
  with_items:
    - "{{ lb_index.results }}"
